---
title: Research
language:
  other-links-title: "Elsewhere on the web:"
format: 
  html:
    lightbox: true
    page-layout: full
    grid: 
      margin-width: 500px
    toc: true
    toc-expand: true
    toc-location: right
    toc-title: Quick Links
    other-links: 
      - text: arXiv
        href: https://arxiv.org/a/0000-0003-3285-9023.html
      - text: YouTube
        icon: youtube
        href: https://www.youtube.com/@shayoolukoya8900/videos
    
    
---
<hr style="opacity:0.1">




On this page, you will find a short description of my research interestes, conference attendances as well as my full list of piblications. For a list of past scientific activites, please see my [CV](./curriculumvitae.pdf){target="_blank"}.




## Research Interests


My primary research interests is in infinite groups, their actions on spaces and their interplay with dynamical systems. 


Currently, I have been particularly interested in generalisations of the Higman-Thompson groups and their connections to shift dynamical systems. 



I am also interested in connections between group theory and theoretical computer science. In particular, decision problems in groups, cellular automata and groups generated by automata.

::: {.column-margin style="position: fixed;"}


::: {.quote-container}

::: {.stylized-quote}

"He took his vorpal sword in hand: <br>
Long time the manxome foe he sought–<br>
So rested he by the Tumtum tree,<br>
And stood awhile in thought."

::: {.quote-attribution}
-- Lewis Carroll

:::

:::

:::

:::




## Funding information


From February 2024 to January 2027 my research is funded by the *Engineering and Physical Sciences Research Council Open postdoctoral fellowship "The Higman-Thompson groups, their generalisations, and automorphisms of shift spaces."*

  

## Publications



### Submitted

<ol reversed>


<li> Conjugacy for certain automorphisms of the one-sided shift via transducers. <br>
C. Bleak, F. Olukoya. <br> 
*Preprint* 	[arXiv:2301.13570](https://arxiv.org/abs/2301.13570), 1-53. </li> 

<li> Automorphisms of shift spaces and the Higman--Thompson groups: the two-sided case. <br> 
C. Bleak, P. Cameron, F. Olukoya. <br>
*Preprint* [arXiv:2006.01466](https://arxiv.org/abs/2006.01466), 1-46.</li>

<li> Automorphisms of shift spaces and the Higman--Thompson groups: extensions. <br>
F. Olukoya. <br>
*Preprint* [arXiv:2407.18720](https://arxiv.org/abs/2407.18720), 1-50. </li> 


<li> An automata theoretic proof that $Out(T_2)$ is isomorphic to $\mathbb{Z}/ 2\mathbb{Z}$ and some embedding results for $Out(V)$. <br>
F. Olukoya. <br>
*Preprint*:  [arXiv:2003.14372](https://arxiv.org/abs/2003.14372), 1-21.</li> 

<li> The core growth of strongly synchronizing transducers. <br>
F. Olukoya. <br>
*Preprint*:  [arXiv:2004.00516](https://arxiv.org/abs/2004.00516), 1-12.</li>


</ol>

### Published
<ol reversed>

<li>    Automorphisms of the generalized Thompson's group.<br>
  F. Olukoya.<br>
  *Trans. London Math. Soc.*, **9**, (2022), 86-135. <br>
  [doi:10.1112/tlm3.12044](https://doi.org/10.1112/tlm3.12044) and [arXiv:1908.03816](https://arxiv.org/abs/1908.03816).</li>

<li>  Automorphisms of shift spaces and the Higman--Thompson groups: the one-sided case. <br>
C. Bleak, P. Cameron, F. Olukoya. <br>
*Discrete Analysis* 2021:15, 35pp.<br>
  [doi:10.19086/da.28243](https://doi.org/10.19086/da.28243) and [arXiv:2004.08478](https://arxiv.org/abs/2004.08478).</li>

<li>  Automorphism tower of groups of homeomorphism of Cantor space.<br>
    F. Olukoya.<br>
    *Israel Journal of Mathematics* Vol. **244**, 883–899 (2021).<br> 
    [doi:10.1007/s11856-021-2196-z]( https://doi.org/10.1007/s11856-021-2196-z) and [arXiv:1908.03815](https://arxiv.org/abs/1908.03815).</li>

<li>  Conjugate subgroups and overgroups of $V_n$. <br> 
    C. Donoven, and F. Olukoya. <br>
    *International Journal of Algebra and Computation* Vol. **30**, No. 6 (2020) 1129--1160. <br> 
    [doi:10.1142/S0218196720500344](https://doi.org/10.1142/S0218196720500344) and [arXiv:1710.00913](https://arxiv.org/abs/1710.00913).</li> 


<li>   The growth rate of automata groups generated by reset automata.<br>
 F. Olukoya.<br> 
 *To appear, Groups Geometry and Dynamics* 1-37.<br> [arXiv:1709.07209](https://arxiv.org/abs/1709.07209).</li>


<li>  The further chameleon groups of Richard Thompson and Graham Higman: automorphisms via dynamics for the Higman groups $G_{n,r}$.<br> 
*To appear, Memoirs of the AMS*, 1-96. <br>
C. Bleak, P. Cameron, Y. Maissel, A. Navas, F. Olukoya. <br>
[arXiv:1605.09302](https://arxiv.org/abs/1605.09302).</li>

</ol>


## Past conference attendances

* _75th British Mathematical Colloquium_, University of Manchester, Manchester, United Kingdom: 17-20 June 2024.
* University of Glasgow, Glasgow, United Kingom: 13-16 May 2024.
*  *GoTh Workshop: Groups of Thompson and their relatives*, University of Magdeburg, Magdeburg, Germany: 18-22 September 2023
* *World of Group Craft*, online, 26 August 2021.
* University of New South Wales, Sydney, Australia: 30 March 2021.
* *Symmetry in Newcastle*, University of Newcastle, Newcastle, Australia: 2 October 2020.
* *Geometric and Asymptotic Group Theory with Applications (GAGTA) 2020 one day workshop*, online: 23 June 2020. 

* University of St Andrews, St Andrews, United Kingdom: 23 June 2020. 
* *Groups generalisations and Applications*, University of Aberdeen, Aberdeen, United Kingdom: 16 January 2019.
* École Normale Supérieure, Paris, France, 4-8 December 2017.


<!-- ## Link to videos with Collin -->
	
