---
title: Teaching
format: 
  html:
    lightbox: true
    page-layout: full
    grid: 
      margin-width: 500px

---


<!-- ## Current Teaching -->

::: {.column-margin}


::: {.quote-container}

::: {.stylized-quote}

"Education either functions as an instrument which is used to facilitate integration of the younger generation into the logic of the present system and bring about conformity or it becomes the practice of freedom..."

::: {.quote-attribution}
-- Paulo Friere, Pedagogy of the Oppressed

:::

:::

:::

:::


## Resources
As a lecturer at University of Keele, I was coordinator for the Group theory, Abstract Algebra, Linear Algebra and Rings modules. I was additionally assigned an introductory data science module which I did not get to deliver. While an associate lecturer at the University of St Andrews, I also coordinated the applied Dynamical Systems module. Resources can be found here.

+   [Group Theory](./Teaching/GroupTheoryNotes/index.html)
+   [Abstract Algebra](./Teaching/AbstractAlgebraNotes/index.html)
+   [Linear Algebra and Rings](./Teaching/LinearAlgebraNotes/index.html)
+   [Dynamical sytems](./Teaching/DynamicalSystemsNotes/index.html)


## Previous Teaching

If you are curious about my teaching history, you can find more details in my [CV](./curriculumvitae.pdf).






